# Generated by Django 5.1 on 2024-08-14 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fungi',
            fields=[
                ('fungi_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=255, unique=True)),
                ('genus', models.CharField(max_length=255)),
                ('family', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('habitat', models.CharField(max_length=255)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='fungi_images/')),
                ('lookalikes', models.CharField(max_length=255)),
                ('toxicity', models.IntegerField(choices=[(6, 'Fatal'), (5, 'Harmful'), (4, 'Edible'), (3, 'Psychoactive'), (2, 'Medicinal'), (1, 'Cullinary'), (0, 'Unknown')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('bio', models.TextField(blank=True, max_length=1000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
