# Generated by Django 5.1 on 2024-08-14 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0002_identified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
