# Generated by Django 5.1 on 2024-08-15 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0003_remove_profile_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.ImageField(upload_to='community_images/')),
                ('location', models.CharField(max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Public'), (2, 'Rejected')], default=0)),
                ('fungi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='id.fungi')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Safety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toxicity', models.IntegerField(choices=[(6, 'Fatal'), (5, 'Harmful'), (4, 'Edible'), (3, 'Psychoactive'), (2, 'Medicinal'), (1, 'Cullinary'), (0, 'Unknown')], default=0)),
                ('precautions', models.TextField()),
                ('symptoms', models.TextField()),
                ('first_aid', models.TextField()),
                ('fungi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='id.fungi')),
            ],
        ),
    ]
