# Generated by Django 5.1 on 2024-08-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0004_communitypost_safety'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identified',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='identified',
            name='location',
        ),
        migrations.RemoveField(
            model_name='identified',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='identified',
            name='time',
        ),
        migrations.RemoveField(
            model_name='identified',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='identified',
            name='list_name',
            field=models.CharField(default='unnamed list', max_length=255),
        ),
        migrations.AddField(
            model_name='identified',
            name='post_id',
            field=models.ManyToManyField(to='id.communitypost'),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Public'), (2, 'Private'), (3, 'Rejected')], default=0),
        ),
        migrations.RemoveField(
            model_name='identified',
            name='fungi_id',
        ),
        migrations.AddField(
            model_name='identified',
            name='fungi_id',
            field=models.ManyToManyField(to='id.fungi'),
        ),
    ]
