# Generated by Django 5.1 on 2024-08-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0006_remove_identified_fungi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True),
        ),
    ]
