# Generated by Django 5.1 on 2024-08-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0007_communitypost_latitude_communitypost_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypost',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, default=None, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, default=None, max_digits=32, null=True),
        ),
    ]
